spring:
  application.name: giovanni
  profiles.include: 'aws-credentials'
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization.WRAP_ROOT_VALUE: true
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    #password: mysqlpass
    url: jdbc:h2:./giovanni_h2
  jpa.hibernate.ddl-auto: update
  #quartz.job-store-type: jdbc

default-locale: en_US

server.port: 9090

---

spring:
  profiles: local
