spring:
  application.name: professor-birch
  profiles.include: 'discord-token'
  jackson.property-naming-strategy: SNAKE_CASE

default-locale: en_US

server.port: 9090

---

spring:
  profiles: local
