spring:
  application.name: giovanni
  profiles.include: 'aws-credentials'
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    #password: mysqlpass
    url: jdbc:h2:./giovanni_h2
  jpa.hibernate.ddl-auto: create
  jackson.parser.ALLOW_COMMENTS: true
  #quartz.job-store-type: jdbc

default-locale: en_US

server.port: 9090

quartz:
  purgeChannels:
    - channel: team-rocket-encounters
      truncateTo: DAYS
      window: PT24H
      cron: '0 0 0 * * ?'
    - channel: sightings
      truncateTo: HOURS
      window: PT1H
      cron: '0 0/5 * * * ?'
    - channel: ex-pass-coordination
      truncateTo: DAYS
      window: PT360H
      cron: '0 0 0 * * ?'
    - channel: legendary-raid-hour
      truncateTo: DAYS
      window: PT192H
      cron: '0 0 0 * * ?'

---

spring:
  profiles: local
