# run git update-index --assume-unchanged src/main/resources/application-aws-credentials.yml
# this file should *NEVER* have your actual aws credentials checked in to git

aws:
  # access-key-id: 
  # secret-key: 
  # profile: 
