spring:
  application.name: giovanni
  profiles.include: 'aws-credentials'
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    #password: mysqlpass
    url: jdbc:h2:./giovanni_h2
  jpa.hibernate.ddl-auto: create
  jackson.parser.ALLOW_COMMENTS: true
  #quartz.job-store-type: jdbc

default-locale: en_US

server.port: 9090

quartz:
  purgeChannels:
    - channel: suggestions
      truncateTo: DAYS
      window: PT24H
      cron: '0 0/5 * * * ?'

---

spring:
  profiles: local
